### ISSUE TITLE
Failed to build cmk docker image.

### ISSUE THREAD

**Issue by mJace** [intel/CPU-Manager-for-Kubernetes#213]
I get an InvocationError when I building cmk.
It shows error like

> "ERROR: InvocationError: '/cmk/.tox/lint/bin/flake8 intel cmk.py tests setup.py'"

I tried the cmk 1.2.2 1.3.0 and master branch with the same result.

the full log is in attachment.
[cmk_error.log](https://github.com/intel/CPU-Manager-for-Kubernetes/files/2510023/cmk_error.log)

**Comment by mJace** [comment]
Ok...  I figured that out.
The root cause for this issue is from latest release of flake8, which is version 3.6.0.
just be released 6 hour ago...

so I change the tox.ini try not to use the latest flake8
```
[testenv:lint]  
deps =  
  flake8  
  pep8-naming
```  

to 
```
[testenv:lint]
deps =
  flake8 == 3.5.0
  pep8-naming
````
the whole building process works fine.

**Comment by przemek-lal** [comment]
Hi @mJace, thanks for reporting this issue. It turns out there was unused variable which was discovered by the latest Flake update. PR #214 should fix the issue.

**Comment by Vladimare** [comment]
Just faced the same issue:

> ERROR: InvocationError: '/cmk/.tox/lint/bin/flake8 intel cmk.py tests setup.py'
