### ISSUE TITLE
problem running the webhook validation test on one node, works fine on other node

### ISSUE THREAD

**Issue by cbf123** [intel/CPU-Manager-for-Kubernetes#236]
I have CMK configured to run on four nodes, controller-0, controller-1, compute-0, compute-1.  All have 4 exclusive CPUs and 1 shared.

If I run the webhook validation test pod with the node specified as "controller-0" it works fine and gets assigned an exclusive CPU.  If I run it against compute-0 the pod fails with the following logs:

controller-0:/tmp$ kubectl logs pod/cmk-isolate-pod
[6] Failed to execute script cmk
/tmp/_MEI1zW97g/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
Traceback (most recent call last):
  File "cmk.py", line 158, in <module>
    main()
  File "cmk.py", line 126, in main
    args["--socket-id"])
  File "intel/isolate.py", line 111, in isolate
    p.cpu_affinity(cpu_list)
  File "site-packages/psutil/__init__.py", line 813, in cpu_affinity
  File "site-packages/psutil/_pslinux.py", line 1508, in wrapper
  File "site-packages/psutil/_pslinux.py", line 1931, in cpu_affinity_set
OSError: [Errno 22] Invalid argument

**Comment by lmdaly** [comment]
@cbf123 Is this node using the latest build CMK image? Quite unusual that it would fail on one of the nodes, looks like a possible issue with the requirements.txt install. Could you try building the CMK image from the master branch?

**Comment by cbf123** [comment]
Sorry, I figured out that the problem was due to the fact that an external management entity had modified the cgroup that dockerd was in, and thus the container was restricted to a limited set of CPUs even though it could see the others.  This caused the underlying sched_setaffinity() syscall to fail when cmk tried to set the affinity to a CPU outside the allowed set.
