### ISSUE TITLE
Add support sriov device numa awarenes

### ISSUE THREAD

**Issue by LilyaBu** [intel/CPU-Manager-for-Kubernetes#243]
CMK should automatically select isolated pool and preferred socket_id in case of container configured with SRIOV network device.  How to find such device inside container? 
One way - to find even one PCIDEVICE_INTEL_COM_<name_of_resource>  variable  among env variables and use its value (pci device address) to detect device`s numa. 
To obtain the pool and socket-id cmk interface could be extended with command sriov_numa_aware and appropriate implementation.

**Comment by lmdaly** [comment]
CMK has no awareness of SRIOV and is not a component that is responsible for aligning resources in a topology aligned manner. There is a --socket-id option that can be supplied to CMK which allows for CPUs to come from a particular socket, using this it should be possible to align the CPUs and SRIOV VFs.

The Topology Manager component planned for the upcoming Kubernetes release will enable this functionality and we are working on supporting this with a variation of CMK.

**Comment by LilyaBu** [comment]
SRIOV device plugin adds PCIDEVICE_INTEL_COM_<name_of_resource> variable inside container env, so current version of CMK does not need aware resources topology, just read PCIDEVICE_INTEL_COM_ env variable and resolve numa of SRIOV device before isolate() invocation.
