### ISSUE TITLE
 webhook.py, line 145, 'requests' should be 'limits' ?

### ISSUE THREAD

**Issue by bqguan** [intel/CPU-Manager-for-Kubernetes#255]
webhook.py, line 145, 'requests' should be 'limits' ?
n_cores = container['resources']['requests'][CMK_ER_NAME]

**Comment by lmdaly** [comment]
Why should it be limits? Extended resources requests must equal limits so it is sufficient to check the resource request.

**Comment by bqguan** [comment]
yes, they should be equal. but why get ER for 2 times in line 140 and line 145? just for try again?

**Comment by lmdaly** [comment]
Ah yes, looking at the code I see what you are referring to. We'll resolve this, thanks for pointing it out!
