### ISSUE TITLE
About why use the pinner binary to pin cpu for a process?

### ISSUE THREAD

**Issue by andyzheung** [intel/CPU-Manager-for-Kubernetes#256]
Hi,  I am interesting in cmk and we have the same request about container also use exclusive core and share core.
      But we always pin a exclusive core to a thread in a process not only on a process, and we pass the exclusive core id to container by docker Environment and let the thread in the process pin this core by themselves. 
     Why this feature is designed only support pin a process to the exclusive core?  and I also see the nokia cpu pooler also design like this.

**Comment by lmdaly** [comment]
Hello! I'm am not sure I am fully understanding here. You would like to be able to pin to an exclusive or a shared core using CMK?

**Comment by andyzheung** [comment]
@

> Hello! I'm am not sure I am fully understanding here. You would like to be able to pin to an exclusive or a shared core using CMK?
I just want to pin a thread in a process using a exclusive core.

**Comment by andyzheung** [comment]
> Hello! I'm am not sure I am fully understanding here. You would like to be able to pin to an exclusive or a shared core using CMK?

I just want to pin a thread in a process using a exclusive core.

**Comment by lmdaly** [comment]
Have you looked at using the --no-affinity option that CMK provides? With this you can request exclusive cores from CMK, but pin the cores to threads from the application itself. https://github.com/intel/CPU-Manager-for-Kubernetes/blob/master/docs/cli.md#cmk-isolate 

Let me know if this would work for you or if you need anything further?

**Comment by andyzheung** [comment]
Thank you so much! 
And I have some doubt about that what is releation between CMK(also CPU Manager for Kubernetes) and CPU Manager in kubernetes?
Current CPU Manager feature is not enough because it can only provide isolate core for guaranteed pod.
![image](https://user-images.githubusercontent.com/22912347/67390076-74040780-f5ce-11e9-9239-144971952285.png)

Will CPU Manager in kubernetes can provide also exclusive core and share in the same pod/containers?
Maybe this question I need to ask in SIG-Node:)

**Comment by andyzheung** [comment]
Thank you so much, I am so interesting in Topology manager. I think I should give the use case to in that topic issue.

**Comment by anvien0111** [comment]
Hi @Imdaly, I want to pin 2 core in exclusive pool to 1 process with cmk isolate command. I change CMK_NUM_CORES=2 but it not work too, do you have any idea?

**Comment by anvien0111** [comment]
@lmdaly Can cmk assign 2 core into 1 process with 'cmk isolate' command? It look like the psutil lib cannot run cpu_affinity() function when I set core in isolate boot grub.

**Comment by maxpain** [comment]
I have a pod, that has two containers.
I want one container to use 1 CPU exclusively with affinity and another container to use a part of a CPU from a shared pool.
Is it possible?
