### ISSUE TITLE
Issue about using hyper-thread in exclusive mode

### ISSUE THREAD

**Issue by thanhlong9x** [intel/CPU-Manager-for-Kubernetes#266]
Hi, I am trying to use CPU pinning for POD using your source. I have successfully installed and tested exclusives mode. It work well, each task run in only one core and no share.
But I have a problem, in each CPU core we have 2 thread like 2-38 and 3-39 but when I start using cmk isolate command, I only see task run in thread 2 and 3 then the next task said core limit, task never run in thread 38 and 39.
Are you support run in mode isolate in thread level or you only support run isolate in core level.
Thanks.
![Capture](https://user-images.githubusercontent.com/29721257/73590619-1bba9b00-4517-11ea-9e1e-60d329fa723c.PNG)
![exclusive](https://user-images.githubusercontent.com/29721257/73590620-1c533180-4517-11ea-9ddc-2916fc2e04c2.png)

**Comment by phillyb7** [comment]
Hi, when using isolate with exclusive mode, CMK isolates on a core level. So, in your example, when the first task requests an exclusive core it takes both of the core's threads (2,38) and assigns them to the task, taking them both out of contention for other tasks to use.

Hope that clears things up.

**Comment by lamto20132223** [comment]
@phillyb7 I read the doc and example, you only talk about assign 1 core to 1 task. When I run cmk to assign multiple core to 1 task, just first core running the task. Can CMK make task run in multi core ?

**Comment by phillyb7** [comment]
Hi @lamto20132223, this problem was also mentioned recently here https://github.com/intel/CPU-Manager-for-Kubernetes/issues/244

We're currently investigating the issue to see if it's an actual bug.

**Comment by lamto20132223** [comment]
Hi @phillyb7 I think this is problem about docker version or something.
When I assign 1 core to task it work perfect, but cannot assign 2 or more cores to 1 task 
Look like taskset has some conflict with isolcpu like this link bellow  
https://github.com/moby/moby/issues/31086
