### ISSUE TITLE
CMK Configmap is hard to manage

### ISSUE THREAD

**Issue by adpempx** [intel/CPU-Manager-for-Kubernetes#289]
Hi guys,

I am using CMK 1.5.1.
Here configmap replaced file-system solution, but the issue here is the configmap is hard-coded inside the python code and that means, it's impossible to manage it inside a helm chart solution. For example, if I remove my CMK helm chart, it can't remove that configmap.

Could you please remove the creation of configmap from python code and create a proper manifest that create it?
Then in the python code, the init will need just to update that configmap instead of create it.

Please let me know as it is blocking my work.

Thanks

**Comment by przemeklal** [comment]
Hi @adpempx, there’s a Helm chart for CMK available here: https://github.com/intel/container-experience-kits/tree/master/roles/cmk_install/charts There’s a bug in there (missing “install” initContainer) but a fix for this is going to be released soon. You can have a look at the Ansible code in that repo to see what are the requirements to install it.

**Comment by adpempx** [comment]
Hi @przemeklal,

I know that helm chart as I am an user of intel container experience kits.
But the issue here is related to this configmap:

https://github.com/intel/CPU-Manager-for-Kubernetes/blob/master/intel/init.py#L41

It's impossible for me for example to change configmap name and/or namespace without change python code.

Could you please fix it?

**Comment by przemeklal** [comment]
I recommend getting in touch with @pbrownlow7 as I am no longer with Intel.

**Comment by pbrownlow7** [comment]
Hi @adpempx, thanks for bringing this to our attention.

Unfortunately the namespace of the configmap is hardcoded as "default", this was an oversight and will be fixed.

Just in terms of changing the configmap name that you mentioned - the name is coded to be "cmk-config-[node-name] to correspond to the node that the configmap represents. It's done like this so cmk can fetch the correct configmap when isolating a pod, so the name needs to remain consistent.

**Comment by adpempx** [comment]
Hi @pbrownlow7,

thanks for your update.

The issue related to configmap is: if I create a helm chart, actually I have all manifests in order to deploy/undeploy CMK helm chart on my system.

But as the configmap is created by python code, when I try to undeploy the CMK helm chart from Kubernetes clusters, helm removes all objects from kubernetes cluster except that cmk-config-[node name] configmap, bucause of course, it has not been created by helm but by python code.

For this reason, it's very hard to produce a CMK helm chart which can create/delete all objects during deployment and undeployment. For example, when I try to undepoy my helm chart, helm deletes everything from kubernetes except that configmap. Then I'll need to remove that configmap manually from kubernetes.

That means helm is not enough in order to deploy/undeploy CMK.

Do you think you can plan to create that configmap from a proper manifest instead from python code? Then the python should only update that configmap.

Please let us know.

Thanks

**Comment by pbrownlow7** [comment]
Thanks for the clarification @adpempx.

Currently cmk's init command presumes that the configmap doesn't exist and tries to create it, which of course, as you described, causes problems when you want this configmap to be created prior. A check could be added to the init command that looks for the existence of a cmk configmap that it can use (based on the _cmk-config-[node-name]_ convention) and if it finds it, simply initializes all of the pools and CPU lists within that configmap, leaving the creation to the user if they need to be the creator.

Does this sound like it would fix the problem you're having?

**Comment by adpempx** [comment]
@pbrownlow7 

Yes, it does. Plus, the fix related to the configmap's namespace. 

In that way, if I can create the configmap by using helm chart, the deployment should work without any issues. Helm can create all objects during the deployment and delete all objects during the undeployment.

When are you planning this change?

Thanks

**Comment by adpempx** [comment]
Hi @pbrownlow7,

do you please have any news?

Thanks

**Comment by pbrownlow7** [comment]
Hi @adpempx, sorry for the delay in replying.

The plan is to include this fix to be a part of the next release, which we hope to release by the end of this week.

Thanks

**Comment by pbrownlow7** [comment]
Hi @adpempx,

Just a quick update, the change has been added in the v1.5.2 release which went out today.

Thanks

**Comment by adpempx** [comment]
Hi @pbrownlow7 

Thanks!

**Comment by pbrownlow7** [comment]
Just an FYI @adpempx, this version will be fully available in the Releases section when the Travis tests finish, but if you need the code you can just clone the latest commit on the repo. I'll close this issue when the tests finish :)

**Comment by adpempx** [comment]
Hi @pbrownlow7,

we have successfully verified CMK 1.5.2.

Thanks for your support!
