### ISSUE TITLE
cmk-cluster-init-pod failed with CreateContainerConfigError

### ISSUE THREAD

**Issue by PrahladaHerle** [intel/CPU-Manager-for-Kubernetes#299]
When the resources/pods/cmk-cluster-init-pod.yaml is applied, pod failed with status 'CreateContainerConfigError'

Pod describe has following message
  Warning  Failed     6s (x4 over 18s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "cmk-cluster-init-pod_cmk-namespace(fa1d4889-e80e-4506-ab08-40e0c50305cf)", container: cmk-cluster-init-pod)

**Comment by DheerajDang** [comment]
```

**Comment by PrahladaHerle** [comment]
@DheerajDang,  with runAsNonRoot: false it's working fine.

**Comment by PrahladaHerle** [comment]
With runAsNonRoot: false issue is resolved.
